# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-05 01:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(default=datetime.datetime(2017, 2, 5, 1, 12, 3, 526967, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 5, 1, 12, 7, 310070, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 5, 1, 12, 13, 729555, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=datetime.datetime(2017, 2, 5, 1, 12, 18, 64782, tzinfo=utc), max_length=80),
            preserve_default=False,
        ),
    ]
